kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
  annotations:
    volume.beta.kubernetes.io/storage-class: SC_NAME 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
