---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-N
  labels:
    app: postgres-N
data:
  POSTGRES_DB: benchdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  PGBENCH_DURATION: "DURATION-N"
  PGDATA: /var/lib/postgresql/data/pgdata

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-N
spec:
  serviceName: "postgres-N"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-N
  template:
    metadata:
      labels:
        app: postgres-N
    spec:
      containers:
      - name: postgres-N
        image: quay.io/tdarnell/px-tme-kubestr-pgbench
        envFrom:
          - configMapRef:
              name: postgres-config-N
        ports:
        - containerPort: 5432
          name: postgres-N
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: postgres-data-N

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-N
  labels:
    app: postgres-N
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-N
